=== dovela/tsuki-button/schema/voice.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "title": "语音名"
      },
      "path": {
        "type": "string",
        "title": "文件名",
        "pattern": "[^*|\\:\"<>?/]+\\.(mp3|wav)+"
      },
      "date": {
        "type": "string",
        "title": "更新时间",
        "format": "date"
      },
      "translate": {
        "type": "object",
        "title": "翻译",
        "properties": {
          "zh-CN": {
            "type": "string",
            "title": "中文翻译"
          },
          "en-US": {
            "type": "string",
            "title": "英文翻译"
          }
        }
      },
      "category": {
        "type": "string",
        "title": "语音分类"
      }
    },
    "required": [
      "name",
      "path",
      "date",
      "translate",
      "category"
    ]
  }
}

=== dovela/tsuki-button/setting/translate/02_dovela_22.08.22.json
[
  {
    "name": "嗷呜",
    "path": "嗷呜.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "嗷呜",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "感觉自己是老头",
    "path": "感觉自己是老头.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "感觉自己是老头",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "嘿！芜！",
    "path": "嘿！芜！.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "嘿！芜！",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "你想要我干嘛",
    "path": "你想要我干嘛.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "你想要我干嘛",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "健康的大笑合集",
    "path": "健康的大笑合集.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "健康的大笑合集",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "弱智才要睡觉",
    "path": "弱智才要睡觉.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "弱智才要睡觉",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我是唱给你们听的",
    "path": "我是唱给你们听的.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "我是唱给你们听的",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "你们根本不知道我在唱什么吧",
    "path": "你们根本不知道我在唱什么吧.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "你们根本不知道我在唱什么吧",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我没急",
    "path": "我没急.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "我没急",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我是鱼",
    "path": "我是鱼.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "我是鱼",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "你们怎么不自己切了",
    "path": "你们怎么不自己切了.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "你们怎么不自己切了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "不要切这个！",
    "path": "不要切这个！.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "不要切这个！",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "还在切？不准切",
    "path": "还在切？不准切.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "还在切？不准切",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "cute but dont cut",
    "path": "cute but dont cut.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "cute but dont cut",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "哼",
    "path": "哼.mp3",
    "date": "2022-8-22",
    "translate": {
      "zh-CN": "哼",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  }
]

=== dovela/tsuki-button/setting/translate/07_dovela_22.09.21.json
[
  {
    "name": "哼③",
    "path": "哼③.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "哼③",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "唱错了重来一遍",
    "path": "唱错了重来一遍.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "唱错了重来一遍",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "不明动物的叫声",
    "path": "不明动物的叫声.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "不明动物的叫声",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "酒鬼的透支与偿还",
    "path": "酒鬼的透支与偿还.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "酒鬼的透支与偿还",
      "en-US": "nya nya nya"
    },
    "category": "梗"
  },
  {
    "name": "会都说不话了",
    "path": "会都说不话了.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "会都说不话了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "嗯？嗯？",
    "path": "嗯？嗯？.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "嗯？嗯？",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "开趴啰",
    "path": "开趴啰.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "开趴啰",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "瑞娅前辈速速给我一个mua",
    "path": "瑞娅前辈速速给我一个mua.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "瑞娅前辈速速给我一个mua",
      "en-US": "nya nya nya"
    },
    "category": "梗"
  },
  {
    "name": "我活啦我复活辣",
    "path": "我活啦我复活辣.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "我活啦我复活辣",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我们算了吧",
    "path": "我们算了吧.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "我们算了吧",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "又唱错了",
    "path": "又唱错了.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "又唱错了",
      "en-US": "nya nya nya"
    },
    "category": "梗"
  },
  {
    "name": "我想要真物",
    "path": "我想要真物.mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "我想要真物",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "网站都可以投(免责声明)",
    "path": "网站都可以投(免责声明).mp3",
    "date": "2022-9.21",
    "translate": {
      "zh-CN": "网站都可以投(免责声明)",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  }
]

=== dovela/tsuki-button/setting/translate/04_dovela_22.08.31.json
[
  {
    "name": "谢谢你关注我mua",
    "path": "谢谢你关注我mua.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "谢谢你关注我mua",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "箔啊",
    "path": "箔啊.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "箔啊",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "要吃什么呢",
    "path": "要吃什么呢.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "要吃什么呢",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "大家一起吃",
    "path": "大家一起吃.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "大家一起吃",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "111真穿吗",
    "path": "111真穿吗.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "111真穿吗",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "啊！水差点泼出来了",
    "path": "啊！水差点泼出来了.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "啊！水差点泼出来了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "哼②",
    "path": "哼②.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "哼②",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我在看着你",
    "path": "我在看着你.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "我在看着你",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我一直都在看着你",
    "path": "我一直都在看着你.mp3",
    "date": "2022-8-31",
    "translate": {
      "zh-CN": "我一直都在看着你",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  }
]

=== dovela/tsuki-button/setting/translate/07_dovela_23.02.04.json
[
  {
    "name": "啊啊啊啊",
    "path": "啊啊啊啊.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "啊啊啊啊",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我tm小孩子证呢",
    "path": "我tm小孩子证呢.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "我tm小孩子证呢",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "不行已经要睡着了",
    "path": "不行已经要睡着了.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "不行已经要睡着了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "好困呀",
    "path": "好困呀.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "好困呀",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "贝壳",
    "path": "贝壳.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "贝壳",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "棉花糖",
    "path": "棉花糖.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "棉花糖",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我的时间好像不多了",
    "path": "我的时间好像不多了.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "我的时间好像不多了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "晚安29秒",
    "path": "晚安29秒.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "晚安29秒",
      "en-US": "nya nya nya"
    },
    "category": "梗"
  },
  {
    "name": "老东西早该414了",
    "path": "老东西早该414了.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "老东西早该414了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "再见了猫奶奶",
    "path": "再见了猫奶奶.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "再见了猫奶奶",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "复活吧小雪",
    "path": "复活吧小雪.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "复活吧小雪",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "复活吧！",
    "path": "复活吧！.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "复活吧！",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "换首吧",
    "path": "换首吧.mp3",
    "date": "2023-2.4",
    "translate": {
      "zh-CN": "换首吧",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  }
]

=== dovela/tsuki-button/setting/translate/06_dovela_22.09.09.json
[
  {
    "name": "《当你》",
    "path": "《当你》.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "《当你》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《那年夏天宁静的海》",
    "path": "《那年夏天宁静的海》.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "《那年夏天宁静的海》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《宁夏》",
    "path": "《宁夏》.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "《宁夏》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《暖暖》",
    "path": "《暖暖》.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "《暖暖》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《情歌》",
    "path": "《情歌》.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "《情歌》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《勇气》",
    "path": "《勇气》.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "《勇气》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《月光》2022.09.06",
    "path": "《月光》2022.09.06.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "《月光》2022.09.06",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《月亮代表我的心》",
    "path": "《月亮代表我的心》.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "《月亮代表我的心》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "嗅嗅",
    "path": "嗅嗅.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "嗅嗅",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "好饿好饿",
    "path": "好饿好饿.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "好饿好饿",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "嗷呜(开瓶版)",
    "path": "嗷呜(开瓶版).mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "嗷呜(开瓶版)",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "拜拜拜拜",
    "path": "拜拜拜拜.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "拜拜拜拜",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "要吐了",
    "path": "要吐了.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "要吐了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "好大的胆子啊",
    "path": "好大的胆子啊.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "好大的胆子啊",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "别发了",
    "path": "别发了.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "别发了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "别睡啦！(音量注意)",
    "path": "别睡啦！(音量注意).mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "别睡啦！(音量注意)",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "不认识捏",
    "path": "不认识捏.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "不认识捏",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "不要再说了(敲桌子)",
    "path": "不要再说了(敲桌子).mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "不要再说了(敲桌子)",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "吃得很饱(大声)",
    "path": "吃得很饱(大声).mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "吃得很饱(大声)",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "烦死了x3",
    "path": "烦死了x3.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "烦死了x3",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "好呀x2",
    "path": "好呀x2.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "好呀x2",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "没醉啦",
    "path": "没醉啦.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "没醉啦",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "醉酒嗝",
    "path": "醉酒嗝.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "醉酒嗝",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "就当巨婴 巨婴怎么了",
    "path": "就当巨婴 巨婴怎么了.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "就当巨婴 巨婴怎么了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "超级清醒",
    "path": "超级清醒.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "超级清醒",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "那我呢",
    "path": "那我呢.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "那我呢",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "主播是否太依赖yyy了",
    "path": "主播是否太依赖yyy了.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "主播是否太依赖yyy了",
      "en-US": "nya nya nya"
    },
    "category": "梗"
  },
  {
    "name": "头疼",
    "path": "头疼.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "头疼",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "晚上好",
    "path": "晚上好.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "晚上好",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "晚上好②",
    "path": "晚上好②.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "晚上好②",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "汪汪汪忘记开麦了",
    "path": "汪汪汪忘记开麦了.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "汪汪汪忘记开麦了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我是小猪",
    "path": "我是小猪.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "我是小猪",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我在看着你们(的弹幕)",
    "path": "我在看着你们(的弹幕).mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "我在看着你们(的弹幕)",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "一直都在",
    "path": "一直都在.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "一直都在",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "营业骗一下舰长",
    "path": "营业骗一下舰长.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "营业骗一下舰长",
      "en-US": "nya nya nya"
    },
    "category": "梗"
  },
  {
    "name": "主播能夹一下吗",
    "path": "主播能夹一下吗.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "主播能夹一下吗",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "主播太1啦",
    "path": "主播太1啦.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "主播太1啦",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "醉酒嗝②",
    "path": "醉酒嗝②.mp3",
    "date": "2022-9.9",
    "translate": {
      "zh-CN": "醉酒嗝②",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  }
]

=== dovela/tsuki-button/setting/translate/03_voices_22.08.29.json
[
  {
    "name": "别在这理发店",
    "path": "别在这理发店.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "别在这理发店",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "吃完小龙虾以后的饱嗝",
    "path": "吃完小龙虾以后的饱嗝.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "吃完小龙虾以后的饱嗝",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "我做我做我做你XX",
    "path": "我做我做我做你XX.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "我做我做我做你XX",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "登山式B动静",
    "path": "登山式B动静.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "登山式B动静",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "要开榨啦",
    "path": "要开榨啦.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "要开榨啦",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "肚子叫了",
    "path": "肚子叫了.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "肚子叫了",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "阿梓谁呀",
    "path": "阿梓谁呀.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "阿梓谁呀",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "嘴里含着点什么的声音",
    "path": "嘴里含着点什么的声音.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "嘴里含着点什么的声音",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  },
  {
    "name": "《夏の花は向日葵だけじゃない》",
    "path": "《夏の花は向日葵だけじゃない》.mp3",
    "date": "2022-8-29",
    "translate": {
      "zh-CN": "《夏の花は向日葵だけじゃない》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  }
]

=== dovela/tsuki-button/setting/translate/05_dovela_22.09.05.json
[
  {
    "name": "《8_32》",
    "path": "《8_32》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《8.32》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《10 YEARS AFTER》",
    "path": "《10 YEARS AFTER》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《10 YEARS AFTER》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《First Love》",
    "path": "《First Love》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《First Love》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《GIRAFFE BLUES》",
    "path": "《GIRAFFE BLUES》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《GIRAFFE BLUES》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《One more time，One more chance》",
    "path": "《One more time，One more chance》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《One more time，One more chance》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《SPiCa》",
    "path": "《SPiCa》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《SPiCa》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《STONES》",
    "path": "《STONES》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《STONES》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《Virtual to LIVE》",
    "path": "《Virtual to LIVE》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《Virtual to LIVE》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《カムパネルラ》（康培内拉）",
    "path": "《カムパネルラ》（康培内拉）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《カムパネルラ》（康培内拉）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《スパークル》（火花）",
    "path": "《スパークル》（火花）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《スパークル》（火花）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《ダークサイドについてきて》（跟我走进心的背面）",
    "path": "《ダークサイドについてきて》（跟我走进心的背面）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《ダークサイドについてきて》（跟我走进心的背面）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《タイムマシン》（时光机）",
    "path": "《タイムマシン》（时光机）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《タイムマシン》（时光机）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《ぼくのフレンド》（我的朋友）",
    "path": "《ぼくのフレンド》（我的朋友）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《ぼくのフレンド》（我的朋友）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《メランコリック》（忧郁症患者）",
    "path": "《メランコリック》（忧郁症患者）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《メランコリック》（忧郁症患者）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《もどかしい世界の上で》（在急不可待的世界上）",
    "path": "《もどかしい世界の上で》（在急不可待的世界上）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《もどかしい世界の上で》（在急不可待的世界上）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《割れたリンゴ》（破碎的苹果）",
    "path": "《割れたリンゴ》（破碎的苹果）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《割れたリンゴ》（破碎的苹果）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《君の知らない物語》（你不知道的故事）",
    "path": "《君の知らない物語》（你不知道的故事）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《君の知らない物語》（你不知道的故事）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《瑠璃色の地球》",
    "path": "《瑠璃色の地球》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《瑠璃色の地球》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《五線譜の空》",
    "path": "《五線譜の空》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《五線譜の空》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《音偽ハナシ》（伪音物语）",
    "path": "《音偽ハナシ》（伪音物语）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《音偽ハナシ》（伪音物语）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《優しさの理由》（温柔的理由）",
    "path": "《優しさの理由》（温柔的理由）.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《優しさの理由》（温柔的理由）",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《真夏の果実》",
    "path": "《真夏の果実》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《真夏の果実》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "《自傷無色》",
    "path": "《自傷無色》.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "《自傷無色》",
      "en-US": "nya nya nya"
    },
    "category": "歌"
  },
  {
    "name": "烦死啦",
    "path": "烦死啦.mp3",
    "date": "2022-9.5",
    "translate": {
      "zh-CN": "烦死啦",
      "en-US": "nya nya nya"
    },
    "category": "日常"
  }
]
